

kandinsky_decoder: "../models/kandinsky-2-2-decoder"
kandinsky_prior: "../models/kandinsky-2-2-prior"
motion_module: "../models/motion-modules/checkpoint-65000.ckpt"

img_h: 768
img_w: 768
video_length: 16

num_inference_steps: 25
guidance_scale: 5
random_seeds: [8311767559332823379, 181945330600420966, 5966451691186754987, 5088790080184097958]

prompts:
  - "cute anime girl looking at the camera, cinematic, 4k, 8k"
  - "pretty girl looking at the camera, extremely high detail, 8k, 4k, cinematic"
  - "mountain river, cinematic, 8k, 4k, HQ"
  - "a cat, cinematic, 8k, 4k, HQ"

n_prompts:
  - "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers"
  - "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers"
  - "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers"
  - "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers"


unet_additional_kwargs:
  use_motion_module: true
  use_inflated_groupnorm: false
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_kwargs:
    num_layers: 2
    num_attention_heads: 8
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
