

kandinsky_decoder: "../models/kandinsky-2-2-decoder"
kandinsky_prior: "../models/kandinsky-2-2-prior"
motion_module: "../models/motion-modules/checkpoint-60000.ckpt"

img_h: 768
img_w: 768
video_length: 16

num_inference_steps: 25
guidance_scale: 5
random_seeds: [8311767559332823379]

prompts:
  - "pretty anime girl looking at the camera, cinematic, 4k, 8k"
  - "pretty girl looking at the camera, cinematic, 8k, 4k"

n_prompts:
  - "lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers"
  - "low quality, bad quality"





unet_additional_kwargs:
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_kwargs:
    num_layers: 2
    num_attention_heads: 8
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
