image_finetune: false

output_dir: "outputs"
pretrained_kandinsky_decoder: "../models/kandinsky-2-2-decoder"
pretrained_kandinsky_prior: "../models/kandinsky-2-2-prior"

unet_additional_kwargs:
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_kwargs:
    num_layers: 2
    num_attention_heads: 8
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path:        "/home/amp2/datasets/webvid/csv/results_2M_train.csv"
  video_folder:    "/home/amp2/datasets/webvid/video"
  sample_size:     256
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 25
  guidance_scale: 4.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: "/home/amp2/Kandimate/outputs/training-2023-09-10T15-42-42/checkpoints/checkpoint-1024.ckpt"

learning_rate:    5.e-5
train_batch_size: 2

max_train_epoch:      -1
max_train_steps:      5120
checkpointing_epochs: -1
checkpointing_steps:  512

validation_steps:       5000
validation_steps_tuple: [2, 512, 1024]

global_seed: 7
mixed_precision_training: true
enable_xformers_memory_efficient_attention: False

is_debug: False
